version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - VITE_API_URL=/api  # Изменено для работы с проксированием
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      server:
        condition: service_healthy

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres.qwspxbbrgizjygzhjgjn:13Elyfamamba13@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      - JWT_SECRET=84ff2284f28cb3db217a4005286a67d033ae194bdb09722b5cd79b515dc3d0d09d1e76cfaba8a199968ea5b3e0cbba4f87869e66afdd772acc10e56ec984b95b
      - CORS_ORIGIN=https://project-two-five.vercel.app,http://localhost
      - PORT=5000
      - NODE_ENV=production
      - PGSSLMODE=require
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
