services:
  client:
    build: ./project_two
    ports:
      - '80:80'
    environment:
      - VITE_API_URL=http://server:5000/api
      - NODE_ENV=production
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network

  server:
    build: ./server_two
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://project_two_admin:PB8T5a1hTMHQcIMfEBlPoQ9MrNNWLGQM@dpg-cvqfe7jipnbc73crlun0-a.frankfurt-postgres.render.com/project_two_db_yhq5
      - JWT_SECRET=84ff2284f28cb3db217a4005286a67d033ae194bdb09722b5cd79b515dc3d0d09d1e76cfaba8a199968ea5b3e0cbba4f87869e66afdd772acc10e56ec984b95b
      - CORS_ORIGIN=https://project-two-five.vercel.app, http://localhost
      - PORT=5000
      - NODE_ENV=production
      - PGSSLMODE=require
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
