FROM node:18-alpine

# Установка curl для healthcheck
RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY . .

CMD ["sh", "-c", "npx prisma migrate deploy && node index.js"]